### ISSUE TITLE
2.2.0

### ISSUE THREAD

**Issue by THEDARKK** [dukesrg/dukesrg.github.io#1]
Hello, it is possible to run
http://dukesrg.github.io/2xrsa.html in 2.2.0?

Thank you

**Comment by b1l1s** [comment]
ROP should run fine, but you need to compile a separate arm11.bin after modifying https://github.com/b1l1s/2xrsa/blob/master/arm11/3ds_utils.11.c#L112

**Comment by THEDARKK** [comment]
Hello, it's possible that you compile it for me?

Thank you

**Comment by b1l1s** [comment]
Never tested, so let me know if it works.

**Comment by THEDARKK** [comment]
No work , i need buy games for update.

**Comment by b1l1s** [comment]
Thanks for letting me know. So sorry that I can't help further.
